enu: &ENU
  listen:
    interface: sps-ics

  icc: &ICC
    #  slit,biasha,rexm,temps,pdu,iis
    ignoreControllers: [ ]

  pdu: &PDU
    mode: operation
    host: pdu-enu{specNum}
    port: 23
    bufferTimeout: 5
    outlets:
      01: port01
      02: port02
      03: slit
      04: ctrl
      05: pows
      06: iis
      07: port07
      08: temps

  biasha: &BIASHA
    mode: operation
    host: biasha-enu{specNum}
    port: 23
    bia_strobe: off
    bia_power: 60
    bia_period: 2000
    bia_duty: 20

  blueshutter:
    host: moxa-enu{specNum}
    port: 4002

  redshutter:
    host: moxa-enu{specNum}
    port: 4003

  slit: &SLIT
    mode: operation
    host: slit-enu{specNum}
    port: 5001
    # home and slit position are defined in the slit coordinate system and then are automatically converted to world
    home: [ 0.0, 0.0, 205.0, 0.0, 0.0, -120 ]
    slit_position: [ -108.0, 0, 262, 0.0, 0.0, -120 ]
    thicknessCarriage: 21.0
    focus_axis: [ 1.0, 0.0, 0.0, 0.0, 0.0, 0.0 ]
    dither_x_axis: [ 0.0, 0.0, 1.0, 0.0, 0.0, 0.0 ]
    dither_y_axis: [ 0.0, 1.0, 0.0, 0.0, 0.0, 0.0 ]
    pix_to_mm: [ 0.035, 0.035 ]
    lowerBounds: [ -5.0,-5.0,-5.0,-1.0,-1.0,-1.0 ]
    upperBounds: [ 5.0,5.0,5.0,1.0,1.0,1.0 ]
    positionTolerance: 0.005  # mm
    accelerationFraction: 0.025 # fraction
    hysteresisCorrection: [ 0.0, 0.0, -0.05, 0.0, 0.0, 0.0 ] # mm, 50 microns against gravity.

  rexm: &REXM
    mode: operation
    host: moxa-enu{specNum}
    port: 4001
    brokenLimitSwitches: False

  temps: &TEMPS
    mode: operation
    host: temps-sm{specNum}
    port: 5025
    biaTempLimit: 30
    doCalib: True

  iis: &IIS
    mode: operation
    host: pdu-iis-enu{specNum}
    port: 9000
    lampNames: [ argon, neon, krypton, halogen ]
    # either aten or digitalLoggers
    pduModel: digitalLoggers

sm1:
  <<: *ENU

  slit:
    <<: *SLIT
    # home and slit position are defined in the slit coordinate system and then are automatically converted to world
    home: [ -0.428, 0.19, 205.080025, 0.0, 0.031776, -120 ]
    slit_position: [ -108.0, 0, 262, 0.0, 0.0, -119.822 ]
    pix_to_mm: [ 0.03447873, 0.03327372 ]
  rexm:
    <<: *REXM
    brokenLimitSwitches: True
  iis:
    <<: *IIS
    lampNames: [ hgar, neon ]
  temps:
    <<: *TEMPS

    101: [ -5.4407785e-06,2.695713e-03,2.1773229e+00,-2.3951511e+02 ]
    102: [ -2.0787244e-05,7.072535e-03,1.7650689e+00,-2.2670118e+02 ]
    103: [ 2.0706686e-05,-5.808919e-03,3.0970679e+00,-2.7263345e+02 ]
    104: [ -1.4876021e-05,5.623519e-03,1.8720407e+00,-2.2885856e+02 ]
    105: [ 4.9744002e-05,-1.482347e-02,4.0301292e+00,-3.0465195e+02 ]
    106: [ 1.1878116e-05,-2.708528e-03,2.7348375e+00,-2.5845745e+02 ]
    107: [ 9.2799664e-06,-1.959793e-03,2.6683692e+00,-2.5670003e+02 ]
    108: [ 1.3447846e-05,-3.177228e-03,2.7857696e+00,-2.6030666e+02 ]
    109: [ -6.6446361e-06,2.604615e-03,2.2354962e+00,-2.4337060e+02 ]
    110: [ -1.4139219e-04,4.505893e-02,-2.2132882e+00,-8.8121236e+01 ]
    201: [ -1.2120787e-05,4.824341e-03,1.9466299e+00,-2.3112438e+02 ]
    202: [ 2.5424163e-05,-6.799760e-03,3.1515878e+00,-2.7277985e+02 ]
    203: [ -1.7765679e-05,6.553557e-03,1.7747321e+00,-2.2549468e+02 ]
    204: [ -3.0759542e-05,1.072078e-02,1.3336658e+00,-2.1002795e+02 ]
    205: [ -4.0283143e-05,1.357006e-02,1.0487171e+00,-2.0056467e+02 ]
    206: [ -1.3079251e-05,5.211183e-03,1.9038820e+00,-2.2970235e+02 ]
    207: [ -1.5409502e-05,5.927586e-03,1.8246291e+00,-2.2655657e+02 ]
    208: [ -1.2818150e-05,5.058727e-03,1.9274403e+00,-2.3070730e+02 ]
    209: [ -4.2382482e-05,1.433515e-02,9.5267900e-01,-1.9648036e+02 ]
    210: [ -3.5955939e-05,1.215674e-02,1.2006535e+00,-2.0591960e+02 ]

  serials:
    fcaId: FCA2

sm2:
  <<: *ENU
  slit:
    <<: *SLIT
    # home and slit position are defined in the slit coordinate system and then are automatically converted to world
    home: [ 0.1134, 0.15, 204.955, -0.15, 0.1402, -120 ]
    pix_to_mm: [ 0.033914, 0.036498 ]

  temps:
    <<: *TEMPS

    101: [ 1.6995258e-05,-4.234013e-03,2.8909288e+00,-2.6405468e+02 ]
    102: [ -3.7966254e-05,1.287539e-02,1.1181054e+00,-2.0268447e+02 ]
    103: [ -1.0575509e-05,4.229621e-03,2.0252092e+00,-2.3425201e+02 ]
    104: [ -2.3603640e-05,8.417461e-03,1.5829689e+00,-2.1887795e+02 ]
    105: [ -2.5704689e-05,9.146367e-03,1.4921009e+00,-2.1510299e+02 ]
    106: [ -2.0286489e-06,1.606628e-03,2.2971255e+00,-2.4395241e+02 ]
    107: [ -1.9577889e-05,7.170654e-03,1.7019499e+00,-2.2261635e+02 ]
    108: [ 1.2354988e-05,-2.647078e-03,2.7137290e+00,-2.5747326e+02 ]
    109: [ -5.7165726e-06,2.928498e-03,2.1335503e+00,-2.3710379e+02 ]
    110: [ 5.8365902e-06,-8.057849e-04,2.5453610e+00,-2.5246653e+02 ]
    201: [ 1.8796767e-05,-4.803445e-03,2.9468594e+00,-2.6559485e+02 ]
    202: [ 4.9980820e-06,-5.024412e-04,2.5039959e+00,-2.5056930e+02 ]
    203: [ 1.3329841e-05,-3.305884e-03,2.8181311e+00,-2.6240531e+02 ]
    204: [ -1.4646948e-05,5.712815e-03,1.8455800e+00,-2.2721913e+02 ]
    205: [ 2.3632074e-05,-6.297986e-03,3.1057056e+00,-2.7140314e+02 ]
    206: [ -7.1797447e-06,3.405692e-03,2.0864475e+00,-2.3567430e+02 ]
    207: [ -1.1792231e-05,4.937003e-03,1.9189480e+00,-2.2967607e+02 ]
    208: [ -1.6761520e-05,6.141217e-03,1.8230473e+00,-2.2703026e+02 ]
    209: [ 6.3029160e-06,-9.857570e-04,2.5606420e+00,-2.5252668e+02 ]
    210: [ -6.3254176e-07,1.187968e-03,2.3348847e+00,-2.4489086e+02 ]

  serials:
    fcaId: FCA4

sm3:
  <<: *ENU
  slit:
    <<: *SLIT
    # home and slit position are defined in the slit coordinate system and then are automatically converted to world
    home : [-0.06, 0.45, 205.075, -0.0249, 0.1915, -120 ]
    #home: [ -0.72, 0.45, 205.075, -0.0249, -0.2985, -120 ] # bad hexapod connection.
    pix_to_mm: [ 0.033914, 0.036498 ]

  temps:
    <<: *TEMPS

    101: [ 8.7415473e-05,-2.629900e-02,5.1945336e+00,-3.4391943e+02 ]
    102: [ 7.1104786e-05,-2.123044e-02,4.6668011e+00,-3.2557376e+02 ]
    103: [ 4.4175855e-05,-1.277263e-02,3.7855592e+00,-2.9507424e+02 ]
    104: [ 4.2332007e-06,-4.569706e-04,2.5205011e+00,-2.5200563e+02 ]
    105: [ 5.4331815e-05,-1.600983e-02,4.1255463e+00,-3.0686826e+02 ]
    106: [ -1.0877718e-06,1.353659e-03,2.3133303e+00,-2.4399324e+02 ]
    107: [ 5.1384900e-05,-1.500842e-02,4.0142409e+00,-3.0287371e+02 ]
    108: [ 4.8162412e-05,-1.406517e-02,3.9224386e+00,-3.0011036e+02 ]
    109: [ 3.3597484e-05,-9.544330e-03,3.4547140e+00,-2.8366619e+02 ]
    110: [ -2.4959021e-05,8.740296e-03,1.5491229e+00,-2.1739907e+02 ]
    201: [ 3.9904669e-05,-1.156438e-02,3.6670583e+00,-2.9104293e+02 ]
    202: [ 3.2294743e-06,-1.574633e-04,2.4920961e+00,-2.5119247e+02 ]
    203: [ 2.7649881e-05,-7.796004e-03,3.2845798e+00,-2.7830852e+02 ]
    204: [ 3.8740226e-05,-1.113488e-02,3.6188217e+00,-2.8936158e+02 ]
    205: [ -4.5696811e-05,1.530873e-02,8.5975000e-01,-1.9373341e+02 ]
    206: [ 3.7062950e-05,-1.077500e-02,3.5966555e+00,-2.8899870e+02 ]
    207: [ 3.4820660e-05,-1.011440e-02,3.5322134e+00,-2.8698634e+02 ]
    208: [ 4.2249051e-05,-1.233004e-02,3.7526593e+00,-2.9432927e+02 ]
    209: [ 2.5201492e-05,-6.891401e-03,3.1759091e+00,-2.7408793e+02 ]
    210: [ 2.6249219e-05,-7.315936e-03,3.2291809e+00,-2.7608946e+02 ]


  serials:
    fcaId: FCA5

sm4:
  <<: *ENU
   
   
  slit:
    <<: *SLIT
    # home and slit position are defined in the slit coordinate system and then are automatically converted to world
    home: [ 0.105, -0.08, 205.1725, -0.099, -0.0598, -120 ]
    slit_position: [ -108.0, 0, 262, 0.0, 0.0, -120 ]

  temps:
    <<: *TEMPS

    101: [ -2.3267846e-05,8.304881e-03,1.5869359e+00,-2.1852054e+02 ]
    102: [ -1.0654807e-05,4.326351e-03,2.0012498e+00,-2.3280609e+02 ]
    103: [ -2.2504248e-05,8.063313e-03,1.6110641e+00,-2.1927577e+02 ]
    104: [ -3.0792648e-05,1.059276e-02,1.3585610e+00,-2.1112955e+02 ]
    105: [ -1.2661619e-06,1.508829e-03,2.2897127e+00,-2.4301098e+02 ]
    106: [ 9.3550468e-06,-1.987157e-03,2.6682914e+00,-2.5637243e+02 ]
    107: [ -3.3416494e-05,1.139426e-02,1.2720592e+00,-2.0805367e+02 ]
    108: [ -6.4838434e-06,3.016539e-03,2.1449062e+00,-2.3827685e+02 ]
    109: [ 2.9403612e-06,9.974992e-05,2.4392152e+00,-2.4818993e+02 ]
    110: [ -8.1989304e-06,3.609929e-03,2.0711243e+00,-2.3513235e+02 ]
    201: [ -3.3432888e-05,1.166108e-02,1.2232671e+00,-2.0557203e+02 ]
    202: [ -1.3039383e-05,5.129689e-03,1.9185085e+00,-2.3005341e+02 ]
    203: [ 7.0845164e-06,-1.145668e-03,2.5690182e+00,-2.5257230e+02 ]
    204: [ -2.0177278e-05,7.328789e-03,1.6896023e+00,-2.2220620e+02 ]
    205: [ 5.6377140e-06,-8.073042e-04,2.5426735e+00,-2.5179142e+02 ]
    206: [ -4.0124425e-08,1.040966e-03,2.3430259e+00,-2.4475910e+02 ]
    207: [ -8.7342594e-06,3.763944e-03,2.0645225e+00,-2.3548628e+02 ]
    208: [ -1.6059798e-05,6.074569e-03,1.8169353e+00,-2.2645864e+02 ]
    209: [ -1.4717237e-05,5.550447e-03,1.8802619e+00,-2.2892191e+02 ]
    210: [ 2.3510685e-05,-6.176995e-03,3.0813002e+00,-2.6994082e+02 ]

  serials:
    fcaId: FCA3
