sps:
  listen:
    interface: sps-ics

  exposure:
    doSyncSpectrograph: True # synchronise spectrograph shutter opening.
    expTimeOverHead: 0 # overhead to calculate the required number of h4 reads.
    ramp:
      nReadMin: 3
      nExtraRead: 1 # EDIT APRIL24 : to be able to synchronise h4 safely, an extra-read was added.

  doUpdateEngineeringFiberStatus: True # set fiberStatus to UNILLUMINATED for unilluminated fibers for eng fibers
  doUpdateScienceFiberStatus: True # set fiberStatus to UNILLUMINATED for unilluminated fibers for science fibers

  S:
    spsModules: [ sm1, sm2, sm3, sm4 ]

    sm1:
      bcu: sci
      rcu: sci
      ncu: none
      rsh: ok
      bsh: ok
      fca: ok
      rda: ok
      bia: ok
      iis: ok

    sm2:
      bcu: sci
      rcu: sci
      ncu: sci
      rsh: ok
      bsh: ok
      fca: ok
      rda: ok
      bia: ok
      iis: ok

    sm3:
      bcu: eng
      rcu: sci
      ncu: sci
      rsh: ok
      bsh: ok
      fca: ok
      rda: ok
      bia: ok
      iis: ok

    sm4:
      bcu: sci
      rcu: sci
      ncu: sci
      rsh: ok
      bsh: ok
      fca: ok
      rda: ok
      bia: ok
      iis: ok

  L:
    spsModules: [ ]
